### ISSUE TITLE
[docs] Polly still in the docs

### ISSUE THREAD

**Issue by kalmarek** [chriselrod/LoopVectorization.jl#109]
just a tiny thing: while Polly is gone from plots it's still referred in text of
https://github.com/chriselrod/LoopVectorization.jl/blob/master/docs/src/examples/matrix_multiplication.md

**Comment by chriselrod** [comment]
Thanks! I'll remove the references to it.

**Comment by chriselrod** [comment]
Removed the references to Polly: https://github.com/chriselrod/LoopVectorization.jl/commit/cc71d9689470b0311184bf8b1372f58ab9a4d0a0

I'd been considering adding [pluto](https://github.com/bondhugula/pluto) in its place. It transforms and optimizes C code using a polyhedral model.

I look forward to adding MLIR, once there's a project ready that makes it easy to use.
The most obvious one is Flang, since I already have Fortran benchmarks, and they're using an MLIR backend, but I don't believe it'll be ready until at least the end of this year.
