### ISSUE TITLE
Reduction with max/min

### ISSUE THREAD

**Issue by mcabbott** [chriselrod/LoopVectorization.jl#130]
I got some strange results when reducing using `max` & friends. This gives the wrong answer, but the equivalent with a reduction `acc = +(acc, Q[i, j, k])` works fine:
```julia
using LoopVectorization, Random

function m!(R::AbstractArray{T}, Q, keep=nothing) where T
    @avx for i in axes(Q,1)
        # acc = -999 # works fine
        acc = ifelse(isnothing(keep), typemin(T), R[i])
        for j in axes(Q,2), k in axes(Q,3)
            acc = max(acc, Q[i, j, k])
        end
        R[i] = acc
    end
    R
end

Q = reshape(shuffle(1:4*5*6),4,5,6);
m!(rand(Int, 4), Q) # [120, 120, 120, 120]
maximum(Q, dims=(2,3)) # right answer

# no problem when reducing along the first dimension:
function n!(R::AbstractArray{T}, Q, keep=nothing) where T
    @avx for j in axes(Q,2)
        acc = ifelse(isnothing(keep), typemax(T), R[j])
        for i in axes(Q,1), k in axes(Q,3)
            acc = min(acc, Q[i, j, k])
        end
        R[j] = acc
    end
    R
end
n!(rand(Int, 5), Q) == vec(minimum(Q, dims=(1,3)))
```
Edit: another minimum, this one an error:
```julia
function m(A::AbstractArray{T}) where T
    acc = typemax(T)
    @avx for i in eachindex(A)
        acc = min(acc, A[i])
    end
    acc
end

m(rand(10)) # MethodError: no method matching vminimum(::NTuple{4,VecElement{Float64}})
```

Unrelated, but here I'm surprised that one-line trinary `?` syntax gets treated differently from the expanded form, it differs only in some `LineNumberNode`s:
```julia
function f!(A, B, z=nothing)
    @avx for i in 1:3
        # a = isnothing(z) ? zero(eltype(A)) : A[i] # this is fine
        acc = if isnothing(z)     # but expanded form is not
            zero(eltype(A))
        else
            A[i]
        end
        A[i] = acc + sqrt(B[i])
    end
    A
end # LoadError: "Expression not recognized:\nbegin\n    #= REPL[541]:5 =#\n    zero(eltype(A))\nend"
f!(rand(3), 4*ones(3))
f!(rand(3), 4*ones(3), 33)

:(true ? 1 : 2) |> dump
:(if true
    1
else
    2
end) |> dump
```

Finally, this ought to be simple but I got a bit lost with different macros in SIMDPirates.jl:
```julia
function g!(A,B)
    @avx for i in 1:3
        # A[i] = trunc(B[i]) # works fine
        A[i] = trunc(Int, B[i])
    end
end
g!(zeros(3), 10randn(3)) # MethodError: no method matching trunc(::Type{Int64}, ::VectorizationBase.SVec{4,Float64})
```

**Comment by chriselrod** [comment]
I've fixed the max/min issues locally (). I'll push soon.

**Comment by chriselrod** [comment]
1) `max` example.
Fixed, [added tests](https://github.com/chriselrod/LoopVectorization.jl/blob/15e889861c386e9c9c33719e2c2349cac807708f/test/miscellaneous.jl#L859).

2) `min` example.
I couldn't reproduce locally. It's now being [tested here](https://github.com/chriselrod/LoopVectorization.jl/blob/15e889861c386e9c9c33719e2c2349cac807708f/test/mapreduce.jl#L48). If after updating to the soon-to-be-registered LoopVectorization 0.8.7 you still see a problem, please try rebuilding your system image, and then file another issue/comment here again if you're still seeing a problem.

3) Ternary vs `if; ...; else; ...; end`
> Unrelated, but here I'm surprised that one-line trinary `?` syntax gets treated differently from the expanded form, it differs only in some `LineNumberNodes`:

The error was:
` # LoadError: "Expression not recognized:\nbegin\n    #= REPL[541]:5 =#\n    zero(eltype(A))\nend" `

The `LineNumberNode` was indeed throwing it off, because it currently only supports 1-line expressions inside if/else statements, and the `LineNumberNode` makes it 2 lines.
Now, it'll walk a `Expr(:block)` looking for something that isn't a `LineNumberNode` (and it'll confirm there's only 1).

As an aside, the reason for the "only 1" limitation is that it'd be messy to try and match all the assignments on both sides of the `else` to make sure they're matched correctly, but it'd certainly be possible to do so. Note that nested expressions are fine: `a = cond ? f(g(h(b,c),bar(d))) : h(b,d)`, because all the intermediate/temps don't need to be matched.
If there are multiple things being matched, multiple lines inside `if; ...; else; ...; end` could be translated to multiple `if/else` statements manually.

It is now [tested here](https://github.com/chriselrod/LoopVectorization.jl/blob/15e889861c386e9c9c33719e2c2349cac807708f/test/ifelsemasks.jl#L82).

4) `trunc`
> Finally, this ought to be simple but I got a bit lost with different macros in SIMDPirates.jl

I plan on eventually moving the functionality to VectorizationBase.jl (abandoning SIMDPirates.jl), and making it all more readable and maintainable in the process. I've also been unhappy with how it's currently set up.

I just realized there was already a `Base.unafe_trunc` definition I should've copied, but I've already registered a new release. The new definition is simply:
```julia
@inline Base.trunc(::Type{I}, v::SVec{W,T}) where {W,I<:Integer,T<:FloatingTypes} = vconvert(SVec{W,I}, v)
```

**Comment by mcabbott** [comment]
Thanks! Can confirm they are all fixed for me now. 

(Sorry about 2, slipped through the double-checking...)

> The new definition is simply:

That looks readable! Eventually I will actually make a PR to this ecosystem...
