### ISSUE TITLE
handling Inf and NaN subsitutions inside of @avx

### ISSUE THREAD

**Issue by guyvdbroeck** [chriselrod/LoopVectorization.jl#142]
Depending on the application, one often needs to define what 0.0/0.0 means, be replacing NaN or Inf in a vector by the appropriate value. For example, my code does:
```
@. scratch = replace_inf_nan(a / b)
@avx @. x += c * d * scratch
```
where `replace_inf_nan(x::T) where T = ifelse((isnan(x) || isinf(x)), zero(T), x)`

I would love to be able to do this at once inside of the `@avx` expression, avoiding the intermediate computation in the `scratch` vector. As I understand it, this is not currently supported? I suppose it would require special support, similar to `exp`.

**Comment by chriselrod** [comment]
```julia
using SIMDPirates # will eventually be `using VectorizationBase` instead
replace_inf_nan(x::T) where T = vifelse(isnan(x) | isinf(x), zero(T), x)
```
Also, do you know `isfinite`?
```julia
replace_inf_nan(x::T) where T = vifelse(isfinite(x), x, zero(T))
```

There are plans to integrate LoopVectorization more with the compiler, but a secondary problem is that, until then, it won't be able to introspect inside your function. It thus assumes the function is relatively costly, like `exp`.
So that's fine if that's true. Otherwise, for now, you'll probably get better performance by writing simple definitions like `vifelse(isfinite(x), x, zero(T))` directly in the loop, to let it more accurately model the costs.

**Comment by guyvdbroeck** [comment]
Wonderful, this works like a charm: code is now 20% faster!
