### ISSUE TITLE
sign Bug?

### ISSUE THREAD

**Issue by hofmannmartin** [chriselrod/LoopVectorization.jl#25]
Hi @chriselrod,

I have been experimenting with the structs and came across something, which seems to be a bug. If I consider the following example
```julia
using StructArrays, Test

function test_native(x, A, k::Int)
    out = zero(T)
    for i ∈ 1:length(x)
        out += A[i,k]*x[i]
    end
    return out
end

function test_struct(xre::Vector{T}, xim::Vector{T}, Are::Matrix{T}, Aim::Matrix{T}, k::Int) where {T<:AbstractFloat}
    zre = zero(T)
    zim = zero(T)
    for i ∈ 1:length(xre)
        zre += xre[i]*Are[i,k] - xim[i]*Aim[i,k]
        zim += xre[i]*Aim[i,k] + xim[i]*Are[i,k]
    end
    return Complex{T}(zre,zim)
end

function test_struct(x::StructVector{Complex{T}}, A::StructArray{Complex{T},2}, k::Int) where {T<:AbstractFloat}
    return test_struct(x.re, x.im, A.re , A.im, k)
end

# set up
T = ComplexF32
M = rand(1:1024)
N = rand(1:1024)

A = StructArray(rand(T,M,N))
b = StructVector(rand(T,M))
k = rand(1:N)
# end set up

@test test_native(b, A, k) ≈ test_struct(b, A, k)
```
everything is fine. However, if I insert the `@avx` macro
```julia
using LoopVectorization

function test_avx(xre::Vector{T}, xim::Vector{T}, Are::Matrix{T}, Aim::Matrix{T}, k::Int) where {T<:AbstractFloat}
    zre = zero(T)
    zim = zero(T)
    @avx for i ∈ 1:length(xre)
        zre += xre[i]*Are[i,k] - xim[i]*Aim[i,k]
        zim += xre[i]*Aim[i,k] + xim[i]*Are[i,k]
    end
    return Complex{T}(zre,zim)
end

function test_avx(x::StructVector{Complex{T}}, A::StructArray{Complex{T},2}, k::Int) where {T<:AbstractFloat}
    return test_avx(x.re, x.im, A.re , A.im, k)
end

@test test_native(b, A, k) ≈ test_avx(b, A, k)
```
The test fails
```
Test Failed at In[2]:17
  Expression: test_native(b, A, k) ≈ test_avx(b, A, k)
   Evaluated: 5.7645955f0 + 234.34486f0im ≈ -5.764599f0 + 234.34473f0im
```
since the real part has wrong sign. Do you have any ideas why?

**Comment by chriselrod** [comment]
There was a bug I used in SIMDPirates that was meant to prevent unnecessary vmovapd instructions the compiler generates in some situations. I just checked if LLVM 9 still does this, and it turns out that (a) it still does and (b) it also still does in the situations where I thought I was preventing it.
So I fixed the bug in that code, but also simply stopped using it.

Now:
```julia
julia> # end set up
       
       @test test_native(b, A, k) ≈ test_struct(b, A, k)
Test Passed
```

**Comment by chriselrod** [comment]
I'll take a look. What version of SIMD pirates are you on?

**Comment by hofmannmartin** [comment]
I am on `SIMDPirates v0.1.6`

**Comment by hofmannmartin** [comment]
I updated to `SIMDPirates v0.1.8`, which solved the issue.

**Comment by chriselrod** [comment]
Someone else was getting errors because the lower bounds prevented upgrading.
You also need upper bounds to automatically register a package.
So the proposed solution was to get rid of the lower bounds and hope the package manager places people on the latest version.

That was obviously the wrong choice. I'll try the multiple-upper-bounds approach next time.

I'll leave this issue open until lower bounds are back in place. You shouldn't have to do it manually.

**Comment by chriselrod** [comment]
Closing now, because I've added lower bounds. LoopVectorization 0.4.0 requires 0.2.0, so the compatible versions should be tied together by the package manager.

I also [added a complex struct of arrays dot to the tests](https://github.com/chriselrod/LoopVectorization.jl/blob/master/test/runtests.jl#L533), so that should guarantee that this example works from now on.
