### ISSUE TITLE
ERROR: UndefVarError: ##op#5321 not defined

### ISSUE THREAD

**Issue by zsoerenm** [chriselrod/LoopVectorization.jl#45]
If I increment an index of one of the variables, I will get the error ##op#5321 not defined
MWE:
```julia
function complex_mul_with_index_offset(a_re, a_im, b_re, b_im, c_re, c_im)
    @avx for i = 1:length(a_re) - 1
        c_re[i] = b_re[i] * a_re[i + 1] - b_im[i] * a_im[i + 1]
        c_im[i] = b_re[i] * a_im[i + 1] + b_im[i] * a_re[i + 1]
    end
end
a_re = ones(Int, 64); a_im = copy(a_re); b_re = copy(a_re); b_im = copy(a_re); c_im = copy(a_re); c_re = copy(a_re)
```
```julia
julia> complex_mul_with_index_offset(a_re, a_im, b_re, b_im, c_re, c_im)
ERROR: UndefVarError: ##op#5321 not defined
Stacktrace:
 [1] sum_with_index_offset(::Array{Int64,1}, ::Array{Int64,1}, ::Array{Int64,1}, ::Array{Int64,1}, ::Array{Int64,1}, ::Array{Int64,1}) at /home/zorn/.julia/packages/LoopVectorization/2jh99/src/reconstruct_loopset.jl:260
```
This does work, however:
```julia
function complex_mul_with_index_offset1(a_re, a_im, b_re, b_im, c_re, c_im)
    @avx for i = 1:length(a_re) - 1
        c_re[i] = b_re[i] * a_re[i + 1] - b_im[i] * a_im[i + 1]
    end
end
```

**Comment by chriselrod** [comment]
Interesting problem, thanks.

`@_avx` instead of `@avx` also works. `@avx` calls a generated function (which can use extra type information to make better decisions), while `@_avx` just transforms the loops (making a few default assumptions about what types there probably are).

There seems to be a mistranslation of the loop as it gets passed to the generated function, but also a problem in the elimination of redundant loads, currently getting confused by the "i + 1" indexing (which is why `a_re[i + 1]` and `a_im[i+1]` only once, as in your second example, works).

I'm still looking into what exactly is going wrong, but I hope to clean this up and fix it fairly soon.

**Comment by chriselrod** [comment]
I fixed this and [added your example to the testsuite](https://github.com/chriselrod/LoopVectorization.jl/blob/master/test/runtests.jl#L199).
