### ISSUE TITLE
Trouble with Float32

### ISSUE THREAD

**Issue by oschulz** [chriselrod/LoopVectorization.jl#6]
With

```julia
function jselfdotavx(a)
    s = zero(eltype(a))
    @inbounds @avx for i ∈ eachindex(a)
        s += a[i] * a[i]
    end
    s
end
```

This works:

```
jselfdotavx(rand(Float64, 1024))
```

but with `Float32`

```julia
jselfdotavx(rand(Float32, 1024))
```

I get

```
ERROR: MethodError: no method matching +(::VectorizationBase.SVec{4,Float32}, ::VectorizationBase.SVec{4,Float64})
[...]
```

**Comment by chriselrod** [comment]
Thanks. Your example should now work on the latest release, but there is still some "trouble with `Float32`", so I'll leave this issue open until at least:

- [ ] No more broadcast issues with Float32.
- [ ] You can define `x_i = zero(eltype(x))` within a for loop, instead of needing to define `x_i = z`, where `z` is set equal to zero outside of the loops. That is:
```julia
function mygemmavx!(C, A, B)
    z = zero(eltype(C))
    @avx for i ∈ 1:size(A,1), j ∈ 1:size(B,2)
        Cᵢⱼ = z
        for k ∈ 1:size(A,2)
            Cᵢⱼ += A[i,k] * B[k,j]
        end
        C[i,j] = Cᵢⱼ
    end
end
```
Is unnecessarily awkward to write.

If any new issues crop up, I can add them to that list.

**Comment by chriselrod** [comment]
I fixed both those problems. So if/when new issues crop up, they should get their own (new) issue.

**Comment by oschulz** [comment]
Thanks for the super-quick fix, @chriselrod!
