### ISSUE TITLE
Transpose and avx broadcast macro

### ISSUE THREAD

**Issue by mcabbott** [chriselrod/LoopVectorization.jl#8]
I'm not sure whether this is expected to work, but right now broadcasting over a transposed matrix gives surprising results:
```
julia> A = randn(2,3); A[2] = 10; At = transpose(A)
3×2 LinearAlgebra.Transpose{Float64,Array{Float64,2}}:
 -0.121486   10.0     
 -1.55957     0.691854
 -0.0858253  -0.918145

julia> exp.(At)
3×2 Array{Float64,2}:
 0.885603  22026.5     
 0.210227      1.99742 
 0.917755      0.399259

julia> @avx exp.(At)
3×2 Array{Float64,2}:
     0.885603  0.210227
 22026.5       1.99742 
     0.210227  0.917755
```

**Comment by chriselrod** [comment]
Thanks, great catch. Fixed and added tests.
https://github.com/chriselrod/LoopVectorization.jl/commit/fa0505bdc2641c8b420be81adbd38ca988ffcbe1

Note that performance will take a hit from the fact you have to either load or store discontiguous elements, but it should still be faster that `exp.(At)`.
Something like `2 .+ At` will probably be slower because `+` is fast relative to the discontiguous loads/stores.

The next commit added support for transposed destinations:
```julia
B = similar(A)
@avx Transpose(B) .= exp.(At)
```
which should be equally as fast as `@avx B .= exp.(A)`.

**Comment by mcabbott** [comment]
Many thanks! 

In looking into `2 .+ At` I stumbled over another error:
```
julia> @btime @avx 2 .+ A
ERROR: MethodError: no method matching add_broadcast!(::LoopVectorization.LoopSet, ::Symbol, ::Symbol, ::Array{Symbol,1}, ::Type{Int64}, ::Int64)

julia> @avx exp.(2 .* A .+ 3)
ERROR: MethodError: no method matching add_broadcast!(::LoopVectorization.LoopSet, ::Symbol, ::Symbol, ::Array{Symbol,1}, ::Type{Int64}, ::Int64)
```
