### ISSUE TITLE
Broadcast errors with powers

### ISSUE THREAD

**Issue by MasonProtter** [chriselrod/LoopVectorization.jl#87]
```julia
julia> using LoopVectorization

julia> xs = rand(100);

julia> @avx xs .^ 2
ERROR: syntax: SSAValue objects should not occur in an AST
Stacktrace:
 [1] top-level scope at REPL[27]:1
 [2] eval(::Module, ::Any) at ./boot.jl:331
 [3] eval_user_input(::Any, ::REPL.REPLBackend) at /home/mason/julia/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
 [4] run_backend(::REPL.REPLBackend) at /home/mason/.julia/packages/Revise/Pcs5V/src/Revise.jl:1073
 [5] top-level scope at none:0

(@v1.4) pkg> st LoopVectorization
Status `~/.julia/environments/v1.4/Project.toml`
  [bdcacae8] LoopVectorization v0.6.29
```

**Comment by chriselrod** [comment]
This is one of the most interesting and least helpful `@macroexpand`s that I've seen:
```julia
julia> @macroexpand @avx xs .^ 2
:($(Expr(:error, "SSAValue objects should not occur in an AST")))
```
Curious about Revise showing up in the stack trace, I tried launching Julia with `--startup=no`:
```julia
julia> @avx xs .^ 2
ERROR: syntax: SSAValue objects should not occur in an AST
Stacktrace:
 [1] top-level scope at REPL[3]:1
```
I expect it to be an easy fix, just curious how strange this SSAValue error is.

**Comment by chriselrod** [comment]
`avx` on broadcasts works by `Meta.lower`-ing the expression:
```julia
julia> Meta.@lower @. foo(a ^ 2 + 3b - c)
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─ %1 = Core.apply_type(Base.Val, 2)
│   %2 = (%1)()
│   %3 = Base.broadcasted(Base.literal_pow, ^, a, %2)
│   %4 = Base.broadcasted(*, 3, b)
│   %5 = Base.broadcasted(+, %3, %4)
│   %6 = Base.broadcasted(-, %5, c)
│   %7 = Base.broadcasted(foo, %6)
│   %8 = Base.materialize(%7)
└──      return %8
))))
```
So that it can swap `materialize(!)` for `vmaterialize(!)`.
Lowering introduces SSA values, so it filtered all the SSA values in the function arguments from the above code info.
I hadn't thought to check if the function itself is a SSA value. But, when constructing the `Val` for the literal pow:
```julia
%2 = (%1)()
```
the function call is in fact an SSA value.

**Comment by MasonProtter** [comment]
Fun!

**Comment by timholy** [comment]
> Curious about Revise showing up in the stack trace

Revise "steals" the REPL so that it calls `revise()` for you before executing whatever you type at the prompt (see https://github.com/timholy/Revise.jl/blob/836d26134161d59dc41430f1d42694777655cfda/src/Revise.jl#L1068-L1073). Consequently, every command you execute is being funneled through Revise.

This will no longer be necessary with Julia 1.5, see https://github.com/timholy/Revise.jl/issues/423.
